{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{- /* The image reads the username out of the variable name. */}}
  ACCOUNT_{{ .Values.auth.username }}: {{ .Values.auth.password | quote }}
  UID_{{ .Values.auth.username }}: {{ .Values.auth.uid | quote }}
{{- end }}
