apiVersion: v2
name: autobrr
description: Filters IRC announce and RSS feeds from private trackers and hands matches to your download client
type: application
version: 0.1.2
# renovate: datasource=docker depName=ghcr.io/autobrr/autobrr
appVersion: "v1.84.0"
kubeVersion: ">=1.25.0-0"
home: https://autobrr.com
icon: https://raw.githubusercontent.com/autobrr/autobrr/master/web/public/logo192.png
sources:
  - https://github.com/autobrr/autobrr
keywords:
  - autobrr
  - torrent
  - irc
  - automation
maintainers:
  - name: Botond Lovasz
    email: botilovasz@gmail.com
annotations:
  artifacthub.io/category: streaming-media
  artifacthub.io/license: Apache-2.0
