{{- if and .Values.config.instances (not .Values.config.existingSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scraparr.fullname" . }}
  labels:
    {{- include "scraparr.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    {{- toYaml .Values.config.instances | nindent 4 }}
{{- end }}
