{{- range $name, $cfg := dict "config" .Values.persistence.config "cache" .Values.persistence.cache }}
{{- if and $cfg.enabled (not $cfg.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" (include "emby.fullname" $) $name }}
  labels:
    {{- include "emby.labels" $ | nindent 4 }}
  {{- $annotations := merge (dict) ($cfg.annotations | default dict) $.Values.commonAnnotations }}
  {{- if $cfg.retain }}
  {{- $annotations = merge (dict "helm.sh/resource-policy" "keep") $annotations }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $cfg.accessMode }}
  resources:
    requests:
      storage: {{ $cfg.size }}
  {{- include "emby.storageClass" (dict "persistence" $cfg "global" $.Values.global "purpose" $name) | nindent 2 }}
{{- end }}
{{- end }}
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) .Values.persistence.media.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-media" (include "emby.fullname" .) }}
  labels:
    {{- include "emby.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) .Values.persistence.media.annotations .Values.commonAnnotations }}
  {{- if .Values.persistence.media.retain }}
  {{- $annotations = merge (dict "helm.sh/resource-policy" "keep") $annotations }}
  {{- end }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.media.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size }}
  {{- include "emby.storageClass" (dict "persistence" .Values.persistence.media "global" .Values.global "purpose" "media") | nindent 2 }}
{{- end }}
