{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "seerr.serviceAccountName" . }}
  labels:
    {{- include "seerr.labels" . | nindent 4 }}
  {{- $annotations := merge (dict) .Values.serviceAccount.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
